<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Nong.Cli</RootNamespace>
    <AssemblyName>nong-pptx</AssemblyName>
    <PackageId>Angri450.Nong.Tool.Pptx</PackageId>
    <ToolCommandName>nong-pptx</ToolCommandName>
    <PackAsTool>true</PackAsTool>
    <Version>12.1.0</Version>
    <Authors>angri450</Authors>
    <Description>PowerPoint operations</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/angri450/Nong.Cli.Net</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.2">
      <IncludeAssets>native</IncludeAssets>
    </PackageReference>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Win32" Version="8.3.1.1">
      <IncludeAssets>native</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="CopySkiaNative" AfterTargets="Publish">
    <ItemGroup>
      <SkiaNative Include="$(NuGetPackageRoot)skiasharp.nativeassets.win32\3.119.0\runtimes\win-x64\native\*.dll" />
      <HarfBuzzNative Include="$(NuGetPackageRoot)harfbuzzsharp.nativeassets.win32\8.3.0\runtimes\win-x64\native\*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(SkiaNative);@(HarfBuzzNative)" DestinationFolder="$(PublishDir)" />
  </Target>
  <ItemGroup>
    <ProjectReference Include="..\PptxCore.csproj" />
    <ProjectReference Include="..\..\Data\Nong.Data.csproj" />
    <ProjectReference Include="..\..\ThirdParty\ThirdParty.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Cli\Commands\PptxCommands.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Cli\Common\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
