<Project>
  <Import Project="$(MSBuildThisFileDirectory)../../OpenXmlData/OpenXmlData.targets" />
  <ItemGroup>
    <OoxGenerator Include="$(MSBuildThisFileDirectory)DocumentFormat.OpenXml.Generator.csproj" />
    <OoxGenerator Include="$(MSBuildThisFileDirectory)../DocumentFormat.OpenXml.Generator.Models/DocumentFormat.OpenXml.Generator.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="@(OoxGenerator)" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" GlobalPropertiesToRemove="TargetFramework" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="@(OpenXmlDataNamespace)" OpenXml="Namespace" LinkBase="OpenXmlData" />
    <AdditionalFiles Include="@(OpenXmlDataSchematron)" OpenXml="Schematron" LinkBase="OpenXmlData" />
    <AdditionalFiles Include="@(OpenXmlDataPart)" OpenXml="Part" LinkBase="OpenXmlData/parts" />
    <AdditionalFiles Include="@(OpenXmlDataSchema)" OpenXml="Schema" LinkBase="OpenXmlData/schema" />
    <AdditionalFiles Include="@(OpenXmlDataTypedNamespace)" OpenXml="TypedNamespace" LinkBase="OpenXmlData/typed" />
    <AdditionalFiles Include="@(OpenXmlDataTypedSchema)" OpenXml="TypedSchema" LinkBase="OpenXmlData/typed" />
  </ItemGroup>
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="OpenXml" />
    <CompilerVisibleProperty Include="DocumentFormat_OpenXml_Generator_NamespaceLookup" />
    <CompilerVisibleProperty Include="DocumentFormat_OpenXml_Generator_Parts" />
    <CompilerVisibleProperty Include="DocumentFormat_OpenXml_Generator_Schemas" />
    <CompilerVisibleProperty Include="DocumentFormat_OpenXml_Generator_Factories" />
    <CompilerVisibleProperty Include="DocumentFormat_OpenXml_Generator_Linq" />
  </ItemGroup>
</Project>